factory_kwargs:
  device: 
  dtype: 

log_config:
verbosity: 1
save_dir: 
name: 
run_id:
predefined: "../config/predefined"

resume:
  expr_path:
  checkpoint:
  epoch: # might be obselete
load_model: 

model:  # if these have to be custom provide a path to the custom config
  use_bn: True
  kernel_transformer: small  # small, medium, large, base
  kernel_function:  # linear, rbf, polynomial, sigmoid, laplacian, exponential
    name: polynomial
    kwargs:    
  embedding: high # basic, medium, high
  classification: 
    mode: 'cls' # cls, seq
    hidden_dim:
    num_hidden_layers:
    activation: relu
    dropout: 0.4

data:
  k: 10 # k-fold cv for lkso
  csv_file: 
  root_dir: 
  biosignals_filtered: True
  classes: [0, 4]
  modalities: #"ecg"
  test_size: 0.2  # if CV is None this signifies the train/test split
  batch_size: 128
  transform: ToTensor
  train_ids: 
  test_ids:

metrics:
  train:
    accuracy_score:
      normalize: True
      sample_weight:
  val:
    f1_score:
      labels:
      pos_labels: 1
      average: binary
      sample_weight:
      zero_division: warn
    recall_score:
      labels:
      pos_labels: 1
      average: binary
      sample_weight:
      zero_division: warn
    precision_score:
      labels:
      pos_labels: 1
      average: binary
      sample_weight:
      zero_division: warn
    accuracy_score:
      normalize: True
      sample_weight:
    #top_k_accuracy_score:
      #labels:
      #k: 1
    
  
criterion:
  name: BCEWithLogitsLoss
  kwargs:
optimizer:
  name: AdamW
  kwargs:
    params:
    lr: 0.001

trainer:
  train_metrics: [accuracy]
  val_metrics: [accuracy, precision, recall, f1] #, top_k]
  modality: 'ecg' # ecg, emg, gsr
  epochs: 10
  from_logits: True